backend:
  name: github
  repo: The-Gas-Station/shared-configs
  branch: prod
  use_graphql: true
  squash_merges: true
publish_mode: editorial_workflow
open_authoring: true
collections:
  - name: "networks"
    label: "Networks"
    identifier_field: "name"
    folder: "public/configs/networks"
    create: true
    extension: "json"
    format: "json"
    fields:
      - {
          label: "Short Name (eth, rinkeby, bsc, polygon, fantom, etc.)",
          name: "name",
          widget: "string",
        }
      - { label: "Display Name", name: "display", widget: "string" }
      - {
          label: "Token Image",
          name: "tokenImage",
          widget: "image",
          allow_multiple: false,
          media_folder: /public/images/tokens,
        }
      - {
          label: "Launched?",
          name: "launched",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Launch Date",
          name: "launchDate",
          required: false,
          widget: "date",
          format: "D MMM, YYYY",
        }
      - {
          label: "Chain ID (1, 4, 56, 137, etc)",
          name: "chainId",
          widget: "number",
        }
      - { label: "CoinGecko", name: "etherCoingeckoId", widget: "string" }
      - {
          label: "Ether/USDC Liquidity Pair",
          name: "etherLiquidityPair",
          required: false,
          widget: "crypto-address",
        }
      - { label: "Gas Token Name", name: "gasTokenName", widget: "string" }
      - {
          label: "Gas Token Address",
          name: "gasTokenAddress",
          required: false,
          widget: "crypto-address",
        }
      - {
          label: "Non-Fungible Patron",
          name: "nfpAddress",
          required: false,
          widget: "crypto-address",
        }
      - {
          label: "Non-Fungible Patron GitHub Base Url",
          name: "nfpGitHubBaseURL",
          required: false,
          widget: "string",
        }
      - { label: "Buy Address", name: "buyAddress", widget: "string" }
      - { label: "Chart Address", name: "chartAddress", widget: "string" }
      - {
          label: "Liquidity Pairs",
          name: "liquidityPairs",
          required: false,
          widget: "list",
          fields:
            [
              { label: "Name", name: "name", widget: "string" },
              { label: "Address", name: "address", widget: "crypto-address" },
            ],
        }
      - {
          label: "Lookup Liquidity Pairs",
          name: "lookupLiquidityPairs",
          required: false,
          widget: "list",
          fields:
            [
              { label: "Name", name: "name", widget: "string" },
              { label: "Address", name: "address", widget: "crypto-address" },
            ],
        }
      - {
          label: "Pools",
          name: "pools",
          required: false,
          widget: "list",
          fields:
            [
              { label: "Name", name: "name", widget: "string" },
              { label: "Address", name: "address", widget: "crypto-address" },
              {
                label: "Type",
                name: "type",
                widget: "select",
                options:
                  ["SingleV1", "SingleV2", "SingleV3", "DoubleV1", "DoubleV2"],
              },
              {
                label: "Stake Symbol Override",
                name: "stakeSymbol",
                required: false,
                widget: "string",
              },
              {
                label: "Stake Token Image",
                name: "stakeIcon",
                widget: "image",
                allow_multiple: false,
                media_folder: /public/images/tokens,
              },
              {
                label: "Reward Symbols Override",
                name: "rewardSymbols",
                required: false,
                widget: "list",
              },
              {
                label: "Reward 0 Token Image",
                name: "reward0Icon",
                widget: "image",
                allow_multiple: false,
                media_folder: /public/images/tokens,
                media_library: { config: { multiple: true } },
              },
              {
                label: "Reward 1 Token Image (for dual reward pools)",
                name: "reward1Icon",
                required: false,
                widget: "image",
                allow_multiple: false,
                media_folder: /public/images/tokens,
              },
            ],
        }
