on:
  push:
    branches:
      - "master"

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Update Website - master
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/61f781ebe61702471f1e98b4
